name: Build App Docker Image

on:
  push:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Build app image
        run: |
          docker build -t app-image:latest -f app/Dockerfile app
          docker save app-image:latest -o app-image.tar

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: app-image
          path: app-image.tar
